config/routes.rb
Rails.application.routes.draw do
  resources :advertisements
  root to: 'advertisements#index'
  devise_for :users
  resources :users
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]
  before_action :verify_user_owns_advertisement, only: [:edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.order('created_at DESC')
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user = current_user

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    @advertisement.user = current_user

    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    def verify_user_owns_advertisement
      if @advertisement.user != current_user
        redirect_to advertisements_url, alert: "That advertisement doesn't belong to you."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:title, :description, :price, :photo)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertisements/_form.html.erb
<%= simple_form_for(@advertisement) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>

  <% if !@advertisement.photo.file.nil? %>
    <p>Current photo:</p>
    <%= image_tag(@advertisement.photo.url) %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/advertisements/edit.html.erb
<h1>Editing Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<nav class='bottom'>
  <%= link_to 'Show', @advertisement %> |
  <%= link_to 'Back', advertisements_path %>
</nav>

app/views/advertisements/index.html.erb
<h1>Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>User</th>
      <th>Time Posted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.title %></td>
        <td><%= advertisement.description %></td>
        <td><%= advertisement.price %></td>
        <td><%= advertisement.user.name %></td>
        <td><%= advertisement.created_at.strftime("%b %-d %l:%M%P %Z") %></td>
        <td><%= link_to 'View', advertisement %></td>
        <% if advertisement.user == current_user %>
        <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
        <td><%= link_to 'Delete', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
<%= link_to 'New Advertisement', new_advertisement_path, { class: "button" } %>
<% end %>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<nav class='bottom'>
<%= link_to 'Back', advertisements_path %>
</nav>

app/views/advertisements/show.html.erb
<div class='advert'>
  <h1>
    <%= @advertisement.title %> | <%= @advertisement.price %>
    <small>Posted by: <%= @advertisement.user.name %></small>
  </h1>


  <p><%= @advertisement.description %></p>

  <% if !@advertisement.photo.file.nil? %>
  <%= image_tag(@advertisement.photo.url) %>
  <% end %>
</div>

<nav class='bottom'>
  <% if @advertisement.user == current_user %>
  <%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
  <% end %>
  <%= link_to 'Back', advertisements_path %>
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Classifieds Foundation" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Classifieds Foundation" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>